const BARES = [
  { visitado: true, bar: "Regô", instagram: "https://www.instagram.com/ao.rego", bairro: "Centro / República", estilo: "Bar Balcão" },
  { visitado: true, bar: "Reguinho", instagram: "https://www.instagram.com/ao.rego", bairro: "Centro / República", estilo: "Bar Balcão" },
  { visitado: true, bar: "Fel", instagram: "https://www.instagram.com/fel.sp", bairro: "Centro / República", estilo: "Alta Coquetelaria" },
  { visitado: true, bar: "Cordial", instagram: "https://www.instagram.com/_cordial_sp", bairro: "Centro / República", estilo: "Bar Boteco" },
  { visitado: false, bar: "Trópico", instagram: "https://www.instagram.com/tropico.sp", bairro: "Centro / República", estilo: "Listening Bar" },
  { visitado: true, bar: "Lágrima", instagram: "https://www.instagram.com/lagrima.bar", bairro: "Centro / República", estilo: "Bar Balcão" },
  { visitado: true, bar: "Matiz", instagram: "https://www.instagram.com/matizbarsp", bairro: "Centro / República", estilo: "Listening Bar" },
  { visitado: true, bar: "Dentro Bar", instagram: "https://www.instagram.com/dentrobarsp", bairro: "Centro / República", estilo: "Bar Boteco" },
  { visitado: true, bar: "Infini Bar", instagram: "https://www.instagram.com/infini.bar", bairro: "Centro / República", estilo: "Speakeasy" },
  { visitado: true, bar: "Virado SP", instagram: "https://www.instagram.com/virado.sp", bairro: "Centro / República", estilo: "Restaurante" },
  { visitado: false, bar: "Formosa Hifi", instagram: "https://www.instagram.com/formosahifi", bairro: "Centro / República", estilo: "Listening Bar" },
  { visitado: true, bar: "Bar dos Arcos", instagram: "https://www.instagram.com/bardosarcos", bairro: "Centro / República", estilo: "Bar Balcão" },
  { visitado: true, bar: "Bargo Mooca", instagram: "https://www.instagram.com/bargomooca", bairro: "Santa Cecília", estilo: "Bar Balcão" },
  { visitado: true, bar: "Aconchegante", instagram: "", bairro: "Santa Cecília", estilo: "Restaurante" },
  { visitado: true, bar: "Das", instagram: "https://www.instagram.com/bar.das.sp", bairro: "Santa Cecília", estilo: "Bar Balcão" },
  { visitado: true, bar: "Koya", instagram: "https://www.instagram.com/koya88", bairro: "Santa Cecília", estilo: "Restaurante" },
  { visitado: true, bar: "Krozta", instagram: "https://www.instagram.com/krozta", bairro: "Santa Cecília", estilo: "Restaurante" },
  { visitado: false, bar: "Café AnarCord", instagram: "https://www.instagram.com/anarcord.sp", bairro: "Jardins", estilo: "Restaurante" },
  { visitado: true, bar: "Riviera", instagram: "https://www.instagram.com/rivierabarerestaurante", bairro: "Jardins", estilo: "Restaurante" },
  { visitado: true, bar: "Raio que o Parta", instagram: "https://www.instagram.com/raioqueopartabar", bairro: "Barra Funda", estilo: "Restaurante" },
  { visitado: false, bar: "Bandeira Bandeira", instagram: "https://www.instagram.com/bandeirabandeirabar", bairro: "Barra Funda", estilo: "Bar Boteco" },
  { visitado: true, bar: "Suei", instagram: "https://www.instagram.com/suei.sp", bairro: "Barra Funda", estilo: "Bar Balada" },
  { visitado: true, bar: "Pina", instagram: "https://www.instagram.com/pina.drinques", bairro: "Barra Funda", estilo: "Bar Boteco" },
  { visitado: true, bar: "Pininha", instagram: "", bairro: "Barra Funda", estilo: "Bar Balcão" },
  { visitado: true, bar: "Trago", instagram: "", bairro: "Barra Funda", estilo: "Bar Boteco" },
  { visitado: true, bar: "Água e Biscoito", instagram: "", bairro: "Barra Funda", estilo: "Listening Bar" },
  { visitado: false, bar: "Por Amor", instagram: "", bairro: "Barra Funda", estilo: "Bar Boteco" },
  { visitado: true, bar: "Sururu", instagram: "", bairro: "Barra Funda", estilo: "Bar Boteco" },
  { visitado: true, bar: "Bar Luiiza", instagram: "", bairro: "Barra Funda", estilo: "Bar Boteco" },
  { visitado: false, bar: "Joio Cocktail Bar", instagram: "", bairro: "Barra Funda", estilo: "Bar Balcão" },
  { visitado: true, bar: "Duas Irmãs", instagram: "", bairro: "Barra Funda", estilo: "Bar Boteco" },
  { visitado: true, bar: "Dopa Bar (em breve)", instagram: "", bairro: "", estilo: "" },
  { visitado: true, bar: "Sala Bar", instagram: "https://www.instagram.com/salabar.sp", bairro: "Pinheiros", estilo: "Bar Balada" },
  { visitado: true, bar: "Boca de Ouro", instagram: "https://www.instagram.com/bocadeourobar", bairro: "Pinheiros", estilo: "Bar Balcão" },
  { visitado: true, bar: "Caledonia", instagram: "", bairro: "Pinheiros", estilo: "Alta Coquetelaria" },
  { visitado: true, bar: "Trinca Bar", instagram: "https://www.instagram.com/trincabar", bairro: "Pinheiros", estilo: "Bar Balcão" },
  { visitado: false, bar: "The Door Bar", instagram: "", bairro: "Pinheiros", estilo: "Bar Balcão" },
  { visitado: false, bar: "CRN 932", instagram: "", bairro: "Pinheiros", estilo: "Restaurante" },
  { visitado: true, bar: "Picco", instagram: "https://www.instagram.com/piccosp", bairro: "Pinheiros", estilo: "Bar Balcão" },
  { visitado: true, bar: "Santana Bar", instagram: "https://www.instagram.com/santanabar.sp", bairro: "Pinheiros", estilo: "Bar Balcão" },
  { visitado: false, bar: "Sylvester", instagram: "", bairro: "Pinheiros", estilo: "Bar Balcão" },
  { visitado: true, bar: "Guarita", instagram: "", bairro: "Pinheiros", estilo: "Bar Boteco" },
  { visitado: true, bar: "Moela Pinheiros", instagram: "", bairro: "Pinheiros", estilo: "Bar Boteco" },
  { visitado: true, bar: "Bar Alto", instagram: "", bairro: "Pinheiros", estilo: "Bar Balada" },
  { visitado: true, bar: "Belle Epoque", instagram: "", bairro: "Pinheiros", estilo: "Bar Balcão" },
  { visitado: true, bar: "Fifty Fifty Bar", instagram: "", bairro: "Pinheiros", estilo: "Bar Balcão" },
  { visitado: true, bar: "SubAstor - Pinheiros", instagram: "https://www.instagram.com/subastor", bairro: "Pinheiros", estilo: "Alta Coquetelaria" },
  { visitado: false, bar: "Alba São Paulo (Vila Beatriz)", instagram: "", bairro: "Pinheiros", estilo: "Restaurante" },
  { visitado: false, bar: "Baretto", instagram: "", bairro: "Jardins", estilo: "" },
  { visitado: false, bar: "Shiro Cocktail", instagram: "https://www.instagram.com/shiro.cocktailbar", bairro: "Jardins", estilo: "" },
  { visitado: false, bar: "Il Covo", instagram: "https://www.instagram.com/ilcovo.bar", bairro: "Jardins", estilo: "Speakeasy" },
  { visitado: false, bar: "Liquorstore", instagram: "", bairro: "Jardins", estilo: "Alta Coquetelaria" },
  { visitado: true, bar: "Flora", instagram: "https://www.instagram.com/flora.bar", bairro: "Jardins", estilo: "Restaurante" },
  { visitado: true, bar: "SubAstor - Paulista", instagram: "https://www.instagram.com/subastor", bairro: "Jardins", estilo: "Alta Coquetelaria" },
  { visitado: true, bar: "Punch Bar", instagram: "https://www.instagram.com/punchbarsp", bairro: "Paraíso", estilo: "Alta Coquetelaria" },
  { visitado: true, bar: "Bar dos Cravos", instagram: "https://www.instagram.com/bardoscravos", bairro: "Paraíso", estilo: "Restaurante" },
  { visitado: true, bar: "Exímia", instagram: "https://www.instagram.com/eximia.bar", bairro: "Itaim / VO", estilo: "Alta Coquetelaria" },
  { visitado: false, bar: "Bar do Naga", instagram: "https://www.instagram.com/bardonaga", bairro: "Itaim / VO", estilo: "Bar Balcão" },
  { visitado: false, bar: "Augustin Bar", instagram: "https://www.instagram.com/augustin.bar", bairro: "Itaim / VO", estilo: "Bar Boteco" },
  { visitado: true, bar: "Cascasse il Mondo Bar", instagram: "https://www.instagram.com/cascasseilmondo", bairro: "Perdizes", estilo: "Restaurante" }
];
