const BARES = [
  { visitado: true, bar: "Regô", instagram: "https://www.instagram.com/ao.rego", bairro: "Centro / República", estilo: "Bar Balcão", lat: -23.5449, lng: -46.6373 },
  { visitado: true, bar: "Reguinho", instagram: "https://www.instagram.com/ao.rego", bairro: "Centro / República", estilo: "Bar Balcão", lat: -23.54347, lng: -46.64036 },
  { visitado: true, bar: "Fel", instagram: "https://www.instagram.com/fel.sp", bairro: "Centro / República", estilo: "Alta Coquetelaria", lat: -23.54749, lng: -46.63857 },
  { visitado: true, bar: "Cordial", instagram: "https://www.instagram.com/_cordial_sp", bairro: "Centro / República", estilo: "Bar Boteco", lat: -23.54252, lng: -46.63697 },
  { visitado: false, bar: "Trópico", instagram: "https://www.instagram.com/tropico.sp", bairro: "Centro / República", estilo: "Listening Bar", lat: -23.54548, lng: -46.6421 },
  { visitado: true, bar: "Lágrima", instagram: "https://www.instagram.com/lagrima.bar", bairro: "Centro / República", estilo: "Bar Balcão", lat: -23.54687, lng: -46.6357, novidadePost: "https://www.instagram.com/p/DaOZtFBv4ki/" },
  { visitado: true, bar: "Matiz", instagram: "https://www.instagram.com/matizbarsp", bairro: "Centro / República", estilo: "Listening Bar", lat: -23.54107, lng: -46.63983 },
  { visitado: true, bar: "Dentro Bar", instagram: "https://www.instagram.com/dentrobarsp", bairro: "Centro / República", estilo: "Bar Boteco", lat: -23.54866, lng: -46.64076 },
  { visitado: true, bar: "Infini Bar", instagram: "https://www.instagram.com/infini.bar", bairro: "Centro / República", estilo: "Speakeasy", lat: -23.54336, lng: -46.63457 },
  { visitado: true, bar: "Virado SP", instagram: "https://www.instagram.com/virado.sp", bairro: "Centro / República", estilo: "Restaurante", lat: -23.54308, lng: -46.64318 },
  { visitado: false, bar: "Formosa Hifi", instagram: "https://www.instagram.com/formosahifi", bairro: "Centro / República", estilo: "Listening Bar", lat: -23.54941, lng: -46.6367 },
  { visitado: true, bar: "Bar dos Arcos", instagram: "https://www.instagram.com/bardosarcos", bairro: "Centro / República", estilo: "Bar Balcão", lat: -23.53994, lng: -46.63724 },
  { visitado: true, bar: "Bargo Mooca", instagram: "https://www.instagram.com/bargomooca", bairro: "Santa Cecília", estilo: "Bar Balcão", lat: -23.5414, lng: -46.6528 },
  { visitado: true, bar: "Aconchegante", instagram: "https://www.instagram.com/aconchegante_bar", bairro: "Santa Cecília", estilo: "Restaurante", lat: -23.53997, lng: -46.65586 },
  { visitado: true, bar: "Das", instagram: "https://www.instagram.com/bar.das.sp", bairro: "Santa Cecília", estilo: "Bar Balcão", lat: -23.54399, lng: -46.65407 },
  { visitado: true, bar: "Koya", instagram: "https://www.instagram.com/koya88", bairro: "Santa Cecília", estilo: "Restaurante", lat: -23.53902, lng: -46.65247 },
  { visitado: true, bar: "Krozta", instagram: "https://www.instagram.com/kroztaaa", bairro: "Santa Cecília", estilo: "Restaurante", lat: -23.54198, lng: -46.6576 },
  { visitado: false, bar: "Café AnarCord", instagram: "https://www.instagram.com/caffeanarcord", bairro: "Jardins", estilo: "Restaurante", lat: -23.5617, lng: -46.6548 },
  { visitado: true, bar: "Riviera", instagram: "https://www.instagram.com/rivierabarsp", bairro: "Jardins", estilo: "Restaurante", lat: -23.56027, lng: -46.65786 },
  { visitado: true, bar: "Raio que o Parta", instagram: "https://www.instagram.com/raioqueoparta.bar", bairro: "Barra Funda", estilo: "Restaurante", lat: -23.5271, lng: -46.6621 },
  { visitado: false, bar: "Bandeira Bandeira", instagram: "https://www.instagram.com/bandeirabandeirabar", bairro: "Barra Funda", estilo: "Bar Boteco", lat: -23.52567, lng: -46.66516 },
  { visitado: true, bar: "Suei", instagram: "https://www.instagram.com/suei.sp", bairro: "Barra Funda", estilo: "Bar Balada", lat: -23.52969, lng: -46.66337 },
  { visitado: true, bar: "Pina", instagram: "https://www.instagram.com/pina.drinques", bairro: "Barra Funda", estilo: "Bar Boteco", lat: -23.52472, lng: -46.66177 },
  { visitado: true, bar: "Pininha", instagram: "https://www.instagram.com/pininha.drinques", bairro: "Barra Funda", estilo: "Bar Balcão", lat: -23.52768, lng: -46.6669 },
  { visitado: true, bar: "Trago", instagram: "https://www.instagram.com/trago_bar", bairro: "Barra Funda", estilo: "Bar Boteco", lat: -23.52907, lng: -46.6605 },
  { visitado: true, bar: "Água e Biscoito", instagram: "https://www.instagram.com/aguaebiscoito", bairro: "Barra Funda", estilo: "Listening Bar", lat: -23.52327, lng: -46.66463 },
  { visitado: false, bar: "Por Amor", instagram: "https://www.instagram.com/botecoporamor", bairro: "Barra Funda", estilo: "Bar Boteco", lat: -23.53086, lng: -46.66556 },
  { visitado: true, bar: "Sururu", instagram: "https://www.instagram.com/obarsururu", bairro: "Barra Funda", estilo: "Bar Boteco", lat: -23.52556, lng: -46.65937 },
  { visitado: true, bar: "Bar Luiiza", instagram: "https://www.instagram.com/luiizabar", bairro: "Barra Funda", estilo: "Bar Boteco", lat: -23.52528, lng: -46.66798 },
  { visitado: false, bar: "Joio Cocktail Bar", instagram: "https://www.instagram.com/joiococktailbar", bairro: "Barra Funda", estilo: "Bar Balcão", lat: -23.53161, lng: -46.6615 },
  { visitado: true, bar: "Duas Irmãs", instagram: "https://www.instagram.com/cervejariaduasirmas", bairro: "Barra Funda", estilo: "Bar Boteco", lat: -23.52214, lng: -46.66204 },
  { visitado: true, bar: "Dopa Bar (em breve)", instagram: "https://www.instagram.com/dopabar.sp", bairro: "", estilo: "", lat: -23.55, lng: -46.633, novidadePost: "https://www.instagram.com/p/DZBISvLIfaE/" },
  { visitado: true, bar: "Sala Bar", instagram: "https://www.instagram.com/salabarsp", bairro: "Pinheiros", estilo: "Bar Balada", lat: -23.5641, lng: -46.684 },
  { visitado: true, bar: "Boca de Ouro", instagram: "https://www.instagram.com/barbocadeouro", bairro: "Pinheiros", estilo: "Bar Balcão", lat: -23.56267, lng: -46.68706 },
  { visitado: true, bar: "Caledonia", instagram: "https://www.instagram.com/caledoniabar", bairro: "Pinheiros", estilo: "Alta Coquetelaria", lat: -23.56669, lng: -46.68527 },
  { visitado: true, bar: "Trinca Bar", instagram: "https://www.instagram.com/trincabar", bairro: "Pinheiros", estilo: "Bar Balcão", lat: -23.56172, lng: -46.68367, novidadePost: "https://www.instagram.com/p/DaQ-wGOHGM9/" },
  { visitado: false, bar: "The Door Bar", instagram: "https://www.instagram.com/thedoor.bar", bairro: "Pinheiros", estilo: "Bar Balcão", lat: -23.56468, lng: -46.6888 },
  { visitado: false, bar: "CRN 932", instagram: "https://www.instagram.com/crn.932", bairro: "Pinheiros", estilo: "Restaurante", lat: -23.56607, lng: -46.6824 },
  { visitado: true, bar: "Picco", instagram: "https://www.instagram.com/o.picco", bairro: "Pinheiros", estilo: "Bar Balcão", lat: -23.56027, lng: -46.68653 },
  { visitado: true, bar: "Santana Bar", instagram: "https://www.instagram.com/_santanabar", bairro: "Pinheiros", estilo: "Bar Balcão", lat: -23.56786, lng: -46.68746 },
  { visitado: false, bar: "Sylvester", instagram: "https://www.instagram.com/sylvesterbarsp", bairro: "Pinheiros", estilo: "Bar Balcão", lat: -23.56256, lng: -46.68127 },
  { visitado: true, bar: "Guarita", instagram: "https://www.instagram.com/guaritabar", bairro: "Pinheiros", estilo: "Bar Boteco", lat: -23.56228, lng: -46.68988 },
  { visitado: true, bar: "Moela Pinheiros", instagram: "https://www.instagram.com/barmoela", bairro: "Pinheiros", estilo: "Bar Boteco", lat: -23.56861, lng: -46.6834 },
  { visitado: true, bar: "Bar Alto", instagram: "https://www.instagram.com/baralto.sp", bairro: "Pinheiros", estilo: "Bar Balada", lat: -23.55914, lng: -46.68394 },
  { visitado: true, bar: "Belle Epoque", instagram: "https://www.instagram.com/belle_epoquesp", bairro: "Pinheiros", estilo: "Bar Balcão", lat: -23.5668, lng: -46.69018 },
  { visitado: true, bar: "Fifty Fifty Bar", instagram: "https://www.instagram.com/fiftyfifty.bar", bairro: "Pinheiros", estilo: "Bar Balcão", lat: -23.56531, lng: -46.68002 },
  { visitado: true, bar: "SubAstor - Pinheiros", instagram: "https://www.instagram.com/subastor", bairro: "Pinheiros", estilo: "Alta Coquetelaria", lat: -23.55934, lng: -46.68883 },
  { visitado: false, bar: "Baretto", instagram: "https://www.instagram.com/fasanosaopaulo", bairro: "Jardins", estilo: "", lat: -23.56429, lng: -46.65607 },
  { visitado: false, bar: "Shiro Cocktail", instagram: "https://www.instagram.com/shirococktailbar", bairro: "Jardins", estilo: "", lat: -23.55932, lng: -46.65447 },
  { visitado: false, bar: "Il Covo", instagram: "https://www.instagram.com/ilcovobar", bairro: "Jardins", estilo: "Speakeasy", lat: -23.56228, lng: -46.6596 },
  { visitado: false, bar: "Liquorstore", instagram: "https://www.instagram.com/theliquorstore.sp", bairro: "Jardins", estilo: "Alta Coquetelaria", lat: -23.56367, lng: -46.6532 },
  { visitado: true, bar: "Flora", instagram: "https://www.instagram.com/florabar.sp", bairro: "Jardins", estilo: "Restaurante", lat: -23.55787, lng: -46.65733 },
  { visitado: true, bar: "SubAstor - Paulista", instagram: "https://www.instagram.com/subastor", bairro: "Jardins", estilo: "Alta Coquetelaria", lat: -23.56546, lng: -46.65826 },
  { visitado: true, bar: "Punch Bar", instagram: "https://www.instagram.com/thepunchsp", bairro: "Paraíso", estilo: "Alta Coquetelaria", lat: -23.573, lng: -46.6474 },
  { visitado: true, bar: "Bar dos Cravos", instagram: "https://www.instagram.com/bardoscravos", bairro: "Paraíso", estilo: "Restaurante", lat: -23.57157, lng: -46.65046 },
  { visitado: true, bar: "Exímia", instagram: "https://www.instagram.com/eximiabar", bairro: "Itaim / VO", estilo: "Alta Coquetelaria", lat: -23.5855, lng: -46.6728 },
  { visitado: false, bar: "Bar do Naga", instagram: "https://www.instagram.com/bardonaga", bairro: "Itaim / VO", estilo: "Bar Balcão", lat: -23.58407, lng: -46.67586 },
  { visitado: false, bar: "Augustin Bar", instagram: "https://www.instagram.com/obaragustin", bairro: "Itaim / VO", estilo: "Bar Boteco", lat: -23.58809, lng: -46.67407 },
  { visitado: true, bar: "Cascasse il Mondo Bar", instagram: "https://www.instagram.com/bar.cascasseilmondo", bairro: "Perdizes", estilo: "Restaurante", lat: -23.5361, lng: -46.6699 }
];
